"""empty message

Revision ID: 1edbb56c4e7d
Revises: bb43284b0c54
Create Date: 2025-08-03 19:13:23.941875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edbb56c4e7d'
down_revision = 'bb43284b0c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_support_user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('public_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_challenges_category'))
        batch_op.drop_index(batch_op.f('ix_challenges_difficulty'))
        batch_op.drop_index(batch_op.f('ix_challenges_public_id'))
        batch_op.create_unique_constraint(None, ['public_id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_support_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_challenges_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_challenges_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_category'), ['category'], unique=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('public_id',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('assigned_support_user_id')

    # ### end Alembic commands ###
