"""Add normalized models

Revision ID: bb43284b0c54
Revises: 92fcd9f33779
Create Date: 2025-07-31 17:24:14.190071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb43284b0c54'
down_revision = '92fcd9f33779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_conversations_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_conversations_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_conversations_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_conversations_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_conversations_identifier'), ['identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_support_conversations_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_conversations_status'), ['status'], unique=False)

    op.create_table('conversation_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('author_display_name', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['support_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_posts_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_posts_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_posts_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_posts_author_user_id'))

    op.drop_table('conversation_posts')
    with op.batch_alter_table('support_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_support_conversations_priority'))
        batch_op.drop_index(batch_op.f('ix_support_conversations_identifier'))
        batch_op.drop_index(batch_op.f('ix_support_conversations_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_conversations_challenge_id'))
        batch_op.drop_index(batch_op.f('ix_support_conversations_category'))
        batch_op.drop_index(batch_op.f('ix_support_conversations_assigned_to_user_id'))

    op.drop_table('support_conversations')
    # ### end Alembic commands ###
