"""Add auth0_id to User

Revision ID: ce6847934b79
Revises: 8f4773851b4a
Create Date: 2025-07-31 13:11:23.590447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6847934b79'
down_revision = '8f4773851b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_id', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['auth0_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auth0_id')

    # ### end Alembic commands ###
